name: Discord-Bot CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  Deploy-application:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ssh server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script : |
            docker stop discord
            cd discord-bot
            git pull
            docker rm discord
            docker rmi discord-bot
            docker build -t "discord-bot" .
            docker run -d --restart=always --name=discord discord-bot
            exit