name: Discord-Bot CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  Deploy application:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ssh server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script : |
            sudo docker stop discord
            ${{ secrets.SSH_PASSWORD }}
            cd discord-bot
            git pull
            sudo docker rm discord
            sudo docker rmi discord-bot
            sudo docker build -t "discord-bot" .
            sudo docker run -d --restart=always --name=discord discord-bot
            exit