name: Discord-Bot CI Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  Test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4
      - name: Setup node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.x
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
      - name: Create .env file
        run: |
          touch .env
          echo BOT_TOKEN_PROD = ${{ secrets.BOT_TOKEN_PROD }} >> .env
          echo BOT_TOKEN_DEV = ${{ secrets.BOT_TOKEN_DEV }} >> .env
          echo prefix = ${{ secrets.PREFIX }} >> .env
          echo TEST_URI = ${{ secrets.TEST_URI }} >> .env
          echo steam_user = ${{ secrets.STEAM_USER }} >> .env
          echo steam_pass = ${{ secrets.STEAM_PASS }} >> .env
          echo steam_name = ${{ secrets.STEAM_NAME }} >> .env
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run eslint
        run: npm run eslint
      - name: Build app
        run: npm run build